---
title: "Salmon to edgeR"
date: '`r format(Sys.time(), "%d %B, %Y")`'
output:
  html_document:
    fig_width: 12
    fig_height: 8
    toc: true
    self_contained: true
---


```{r setup, include=FALSE, cache = F}
#.rs.restartR()
#Setup
knitr::opts_knit$set(
  root.dir = '/Users/bbitarello/Documents/GitHub/Ehux_Ehv201/', 
  error = T,
  cache = F, 
  echo = F,
  fig.showtext = TRUE,
  tidy = TRUE,
  message = FALSE,
  collapse = TRUE,
  dev = 'pdf')



## Fonts and figures settings
source("~/Documents/GitHub/Ehux_Ehv201/dge/pkgs.R")
source("~/Documents/GitHub/Ehux_Ehv201/dge/plot_funcs.R")
source("~/Documents/GitHub/Ehux_Ehv201/dge/Functions.R")

# conflicts between packages
conflicts_prefer(dplyr::filter)
conflicts_prefer(dplyr::rename)
conflicts_prefer(dplyr::select)
```

# Setups

```{r, setup2, eval = T, echo = F, include = T}
## Adjust these to your actual file paths
## Working directory
base_path <- "~/Documents/Ehux-for-pub/scratch/"
## Salmon path
base_path2 <- "~/Documents/Ehux-for-pub/salmonQ-v1.11.4/"

## Select subset of genes to look at. 

## Options: 
#subs <- "virus"; sampSet <- "39samp" #
#subs <- "virus"; sampSet <- "29samp"  # 
#subs <- "virus"; sampSet <- "20samp" #
#subs <- "virus"; sampSet <- "10samp" #
#subs <- "host";  sampSet <- "76samp" #

res_path <- paste0(base_path, subs, "/", sampSet, "/")
(ext <- paste0("_", sampSet,"_", subs))


if(subs == 'virus'){
trt_vir_cols<- trt_vir_cols[c(2,4)]
}

## Order time points correctly for plots
levs<-c("45min", "3h", "8h", "24h")
if(sampSet == "29samp"){
  levs<-levs[-1]
}
if(sampSet == "20samp"){
  levs<-levs[-c(1:2)]
}
if(sampSet == "10samp"){
  levs<-levs[-c(1:3)]
}
```


# Read in data

```{r, read-salmon-data, echo = T, cache = F}


#FINAL COLDATA PLEASE CHECK!
coldata <- read_tsv(paste0("data/coldata_", sampSet, ".txt"),show_col_types = FALSE)

salmon_files <- readRDS(paste0(base_path, "data/salmon_files_", sampSet, ".RDS"))
#check
#table(names(salmon_files)==sample_meta$names)
# Read in annotation data ----

Sys.setenv(VROOM_CONNECTION_SIZE = 500000L)
if(TRUE){ #updated with new host annot 07/21/25
if(subs == 'virus'){
#just virus
annot<-readRDS(paste0(base_path, "data/Annotations-", subs, "/annot_", subs, "4.rds"))
  annot<-annot |> mutate(rowLabel = accession, .after = locus_tag)
}else if(subs == "host"){
annot<-readRDS(paste0(base_path, "data/Annotations-", subs, "/annot_", subs, "3.rds"))

(dup_annot <- annot |> 
    group_by(locus_tag) |> 
    tally() |> 
    filter(n>1) |> 
    pull(locus_tag))

annot<-annot |> mutate(rowLabel =
           case_when(
             is.na(Symbol) == F ~ Symbol,
             is.na(Symbol) == T ~ locus_tag
           ),
         .after = "Symbol")
#check
annot |> group_by(locus_tag) |> summarise(N=length(unique(rowLabel))) |>filter(N>1)
saveRDS(annot, file = paste0(base_path, "data/annot_", subs, "_edgeR.rds"))
}
}
# if(FALSE){
# Sys.setenv(VROOM_CONNECTION_SIZE = 500000L)
# 
# if(subs == 'virus'){
# #just virus
# annot<- data.table::fread(paste0(base_path, "data/annot_virus_ext.tsv"), na.strings = c("", NA)) |> as_tibble() |> 
#   mutate(rowLabel = accession, .after = "gene_id")
# cdna_v<-readRDS(paste0(base_path, "data/cdna_virus.rds"))
# }else if(subs == "host"){
# #host has some genes with more than one transcript.
# #annot<- data.table::fread(paste0(base_path, "data/annot_host.gz")) |> as_tibble() 
# annot <- read_tsv(paste0(base_path, "data/annot_host_ext.tsv"), show_col_types = FALSE)
# annot<-annot |> 
#   mutate(gene_symbol = ifelse(gene_symbol=="", NA, gene_symbol))
# (dup_annot <- annot |> 
#     group_by(gene_id) |> 
#     tally() |> 
#     filter(n>1) |> 
#     pull(gene_id))
# # fix these entries to avoid ambiguity
# for(g in dup_annot){
#   tmp <- annot |> filter(gene_id == g)
#   #tmp2<-paste0(tmp$gene_id, "-", 1:nrow(tmp))
#   tmp3<-paste0(tmp$rowLabel, "-", 1:nrow(tmp))
#   #tmp4<-paste0(tmp$description, collapse = "; ")
#   annot$rowLabel[which(annot$gene_id == g)]<-tmp3
#   
#   annot$gene_id[which(annot$gene_id == g)]<-tmp2
#   remove(tmp, tmp2, tmp3)
#   }
# 
# (dup_annot2 <- annot |> group_by(rowLabel) |> tally() |> filter(n>1) |> pull(rowLabel))
# 
# for(g in dup_annot2){
#   tmp <- annot |> filter(rowLabel == g)
#   tmp2<-paste0(tmp$rowLabel, "-", 1:nrow(tmp))
#   annot$rowLabel[which(annot$rowLabel == g)]<-tmp2
#   remove(tmp, tmp2)
# }
# 
# ## long rowLabels
# 
# (longLab<- annot |> filter(is.na(gene_symbol)==F) |> filter(nchar(rowLabel)>35) |> pull(rowLabel))
# 
# for(l in longLab){
#   tmp <- annot |> filter(rowLabel == l)
#   tmp2<-tmp$gene_id
#   annot$rowLabel[which(annot$rowLabel == l)]<-tmp2 
# }
# annot<-annot |> 
#   rename(`GO_BP` = `GO (biological process)`) |> 
#   rename(`GO_CC` = `GO (cellular component)`) |> 
#   rename(`GO_MF` = `GO (molecular function)`)
# }
# nrow(annot) == length(unique(annot$gene_id))
# nrow(annot) == length(unique(annot$rowLabel))
# gc()
# 
# annot<-annot |> rename(tx_id = transcript_id)
# saveRDS(annot, paste0(base_path, "data/annot", "_", subs, ".rds"))
# openxlsx::write.xlsx(annot, paste0(base_path, "data/annot-", subs, "-ext.xlsx"))
# }else{
# annot<-readRDS(paste0(base_path, "data/annot", "_", subs, ".rds"))
# }
#   

```



# Prep

```{r edger-prep, eval = T, echo = T, cache = F}
library(edgeR)
## https://github.com/bartongroup/profDGE48/blob/master/DE_tool_scripts/edgeR.R
## https://support.bioconductor.org/p/84338/
## https://support.bioconductor.org/p/84291/#84292
## https://bioconductor.statistik.tu-dortmund.de/packages/3.6/bioc/vignettes/tximport/inst/doc/tximport.html#edger
## and edgeR user's guide: https://web.stanford.edu/class/bios221/labs/rnaseq/lab_4_rnaseq.html
## Make table for tximport: transcript to Gene map: https://bioconductor.org/packages/devel/bioc/vignettes/tximport/inst/doc/tximport.html#edgeR
if(subs == 'host'){
tx_to_gene <- annot |> 
  dplyr::select(tx_id, locus_tag, rowLabel, tx_name, GeneName, Symbol, NrTranscripts)
}else{
tx_to_gene <- annot |> 
  dplyr::select(tx_id, locus_tag, rowLabel, everything())
}

if(TRUE){
txi <- tximport::tximport(salmon_files, 
        type = "salmon", 
        tx2gene = tx_to_gene)
saveRDS(txi, file = paste0(res_path, "txi", ext, ".rds"))
}else{
txi<-readRDS(file = paste0(res_path, "txi", ext, ".rds"))
}
cts <- txi$counts
normMat <- txi$length
## Obtaining per-observation scaling factors for length, adjusted to avoid
## changing the magnitude of the counts.
normMat <- normMat/exp(rowMeans(log(normMat)))
normCts <- cts/normMat
## Computing effective library sizes from scaled counts, to account for composition biases between samples.
eff.lib <- calcNormFactors(normCts) * colSums(normCts)
## Combining effective library sizes with the length factors, and calculating offsets for a log-link GLM.
normMat <- sweep(normMat, 2, eff.lib, "*")
normMat <- log(normMat)

## Creating a DGEList object for use in edgeR.
y <- DGEList(cts)
y <- scaleOffset(y, normMat)
```

# QC

## QC plots BEFORE filtering out genes


```{r, edgeR-QC-lib, fig.width=12}

## Check Library Size and Distribution ----
## https://seq-jchoi-bio.github.io/docs/RNASeq/DEG_edgeR_MANUAL/
## the values are converted to non-zero values.
if(TRUE){
pseudoCounts <- log2(y$counts+1) 

FullCol <- as.numeric(factor(coldata$condition, ordered = T)) + 1
if(subs == 'virus'){
colnames(pseudoCounts)<-gsub("_inf_", "_",colnames(pseudoCounts))
names(FullCol)<-colnames(pseudoCounts)
pivot_longer(as.data.frame(pseudoCounts), cols = colnames(pseudoCounts)) |> 
    mutate(SplitSampleName(name)) |>
  select(name, value, trt, timePt)  |>  
  mutate(name = gsub("(DMSO|HHQ)_t(1|2|3|4)_", "", name)) |> rename(Replicate = name) |>
  mutate(timePt=factor(PrepNamesForPlots(timePt=paste0("t", timePt))$timePt, levels = levs, ordered = T))|>
           ggplot(aes(x = Replicate, y = value, fill = trt)) + 
  geom_boxplot(alpha = 0.6) + 
  facet_grid(rows = vars(trt), cols = vars(timePt)) + scale_fill_manual(values = trt_vir_cols) +
  bb_theme() + 
  ylab("log2(counts+1)") +
  theme(axis.text.x = element_text(angle = 90, size = 8,vjust = 1))
ggsave(paste0(res_path, "figs/edgeR_pseudocounts_boxplot_BefFilt", ext, ".pdf"), device = cairo_pdf)


pivot_longer(as.data.frame(pseudoCounts), cols = colnames(pseudoCounts)) |> 
    mutate(SplitSampleName(name)) |> 
  select(name, value, trt, timePt)  |>  
  mutate(name = gsub("(DMSO|HHQ)_t(1|2|3|4)_", "", name)) |> 
  rename(Replicate = name) |>
  mutate(timePt=factor(PrepNamesForPlots(timePt=paste0("t", timePt))$timePt, levels = levs, ordered = T))|>
           ggplot(aes(x = Replicate, y = value, fill = trt)) + 
  geom_violin(alpha = 0.6,trim = T,draw_quantiles = 0.5) + 
  facet_grid(rows = vars(trt), cols = vars(timePt)) +
scale_fill_manual(values = trt_vir_cols) + 
  bb_theme() + 
  ylab("log2(counts+1)") + 
  theme(axis.text.x = element_text(angle = 90, size = 8,vjust = 1))

ggsave(paste0(res_path, "figs/edgeR_pseudocounts_violin_BefFilt", ext, ".pdf"), device = cairo_pdf)
}else{
names(FullCol)<-colnames(pseudoCounts)

pivot_longer(as.data.frame(pseudoCounts), cols = colnames(pseudoCounts)) |> 
    mutate(SplitSampleName(name)) |>
  mutate(trt_vir = paste0(trt, " (", virus, ")")) |>
  select(name, value, trt_vir, timePt)  |>  
  mutate(name = gsub("(DMSO|HHQ)_(cntl|inf)_t(1|2|3|4)_", "", name)) |> rename(Replicate = name) |>
  mutate(timePt=factor(PrepNamesForPlots(timePt=paste0("t", timePt))$timePt, levels = levs, ordered = T))|>
           ggplot(aes(x = Replicate, y = value, fill = trt_vir)) + 
  geom_boxplot(alpha = 0.6) + 
  facet_grid(rows = vars(trt_vir), cols = vars(timePt)) + scale_fill_manual(values = trt_vir_cols) +
  bb_theme() + 
  ylab("log2(counts+1)") +
  theme(axis.text.x = element_text(angle = 90, size = 8,vjust = 1))

ggsave(paste0(res_path, "figs/edgeR_pseudocounts_boxplot_BefFilt", ext, ".pdf"), device = cairo_pdf, width = 12)

pivot_longer(as.data.frame(pseudoCounts), cols = colnames(pseudoCounts)) |> 
    mutate(SplitSampleName(name)) |> 
   mutate(trt_vir = paste0(trt, " (", virus, ")")) |>
  select(name, value, trt_vir, timePt)  |>  
  mutate(name = gsub("(DMSO|HHQ)_(cntl|inf)_t(1|2|3|4)_", "", name)) |> rename(Replicate = name) |>
  mutate(timePt=factor(PrepNamesForPlots(timePt=paste0("t", timePt))$timePt, levels = levs, ordered = T))|>
           ggplot(aes(x = Replicate, y = value, fill = trt_vir)) + 
  geom_violin(alpha = 0.6,trim = T,draw_quantiles = 0.5) + 
  facet_grid(rows = vars(trt_vir), cols = vars(timePt)) +
scale_fill_manual(values = trt_vir_cols) + 
  bb_theme() + 
  ylab("log2(counts+1)") + 
  theme(axis.text.x = element_text(angle = 90, size = 8,vjust = 1))

ggsave(paste0(res_path, "figs/edgeR_pseudocounts_violin_BefFilt", ext, ".pdf"), device = cairo_pdf, width = 12)  
}

# pdf(paste0(res_path, "pseudoCounts_BefFilt", ext, ".pdf"))
# pbox<-boxplot(pseudoCounts, col=FullCol, las=2) 
#   abline(h=median(as.matrix(pseudoCounts)), col="blue") # Save boxplot
# dev.off()
# plot(pbox)


# Heatmaps & PCAs ----

cpm_log <- cpm(y$counts, log = TRUE)
if(subs == 'virus'){
colnames(cpm_log)<-gsub("_inf_", "_", colnames(cpm_log))
}
dmat<-round(stats::cor(cpm_log, method = "spearman"),4)

#Transform the scale from correlations
ddist<-round((-(dmat-1)/2),4)
ddist<-as.dist(ddist)
pheatmap1<-MyPheatmapDist(dmat,color = prgn, main = "Correlation of log(CPM), unfiltered genes", clustering_distance_cols = ddist , clustering_distance_rows = ddist)
save_pheatmap_png(pheatmap1,paste0(res_path, "figs/edgeR_heatmap1_cpmLog_corr_BefFilt", ext, ".png"), width=1600)

library("PoiClaClu")
if(sampSet != "39samp"){
poisd <- PoissonDistance(t(cts), type = 'deseq')
}else{
poisd <- PoissonDistance(t(cts), type = 'mle')
}
samplePoisDistMatrix <- as.matrix( poisd$dd )
rownames(samplePoisDistMatrix)<-colnames(normMat)
colnames(samplePoisDistMatrix)<-colnames(normMat)
ppois_g<-MyPheatmapDist(samplePoisDistMatrix,
         clustering_distance_rows=poisd$dd,
         clustering_distance_cols=poisd$dd, main = "Poisson distance of raw counts, unfiltered genes")
save_pheatmap_png(ppois_g,paste0(res_path, "figs/edgeR_heatmap2_PoisDistRaw_BefFilt", ext, ".png"), width=1600)

metadata <- data.frame(row.names = colnames(cpm_log))
metadata$trt_vir<-coldata$trt_vir
metadata$timePt <- coldata$timePt

if(subs == 'virus'){
ntop <- nrow(cpm_log) 
nprop <-0.90
}else{
nprop<-0.50
ntop <-round(nprop*nrow(cpm_log))
}
p <- PCAtools::pca(
            mat = cpm_log,
            metadata = metadata,
            removeVar = 1-nprop) # 

rownames(p$loadings) <- as_tibble(rownames(p$loadings)) |>
  setNames("locus_tag") |>
  left_join(annot) |>
  dplyr::select(c("rowLabel")) |>
  unique() |>
  deframe() 
pdf(paste0(
  res_path, "figs/edgeR_PCAbiplots_condition",
  ext,
  "_0_BefFilt.pdf"
))
ppca0a <- PCAtools::biplot(
  p,
  showLoadings = FALSE,
  x = "PC1",
  y = "PC2",
  colby = 'trt_vir',
  shape = 'timePt',
  # to change shape by levels of an additional factor
  legendPosition = 'right',
  labSize = 2,
  pointSize = 2,
  sizeLoadingsNames = 2,
  title = "Not so pretty PCA"
)

ppca0b <- PCAtools::biplot(
  p,
  showLoadings = T,
  x = "PC1",
  y = "PC2",
  colby = 'trt_vir',
  shape = 'timePt',
  # to change shape by levels of an additional factor
  legendPosition = 'right',
  labSize = 2,
  pointSize = 2,
  sizeLoadingsNames = 2,
  title = "Not so pretty PCA",
  ntopLoadings = 3
)

ppca0a
ppca0b
dev.off()
ppca0a
ppca0b
}
```

## QC after filtering out genes

```{r, edgeR-filt}

## Specify design ----
if(TRUE){
#design <- model.matrix(~0 + batch + condition, data = coldata)
#design <- model.matrix(~0 + condition + batch, data = coldata)
group <- fct_inorder(coldata$condition)
design <- model.matrix(~0 + group)
#colnames(design) <- sub("batch", "", colnames(design))
#colnames(design) <- sub("condition", "", colnames(design))
colnames(design) <- sub("group", "", colnames(design))
colnames(design)
y$samples$group<-group
# filtering using the design information
#if(!(identical(coldata$names, colnames(design)))){stop("!!")}
keep <- filterByExpr(y, design)
table(keep) #host: 28083 
y2 <- y[keep, ]
cat('Filtered out ', nrow(y)-nrow(y2),  'genes, ', nrow(y2), ' genes are left.', 
'\n')

saveRDS(keep, paste0(res_path, "edgeR_keep", ext, ".rds"))
saveRDS(y2,  paste0(res_path, "FiltObj", ext, ".rds"))
# y2 is now ready for estimate dispersion functions see edgeR User's Guide


## Plots after filtering out genes ---
## 1. Lib size

pseudoCounts <- log2(y2$counts+1) 

FullCol <- as.numeric(factor(coldata$condition, ordered = T)) + 1
if(subs == 'virus'){
colnames(pseudoCounts)<-gsub("_inf_", "_",colnames(pseudoCounts))
names(FullCol)<-colnames(pseudoCounts)
pivot_longer(as.data.frame(pseudoCounts), cols = colnames(pseudoCounts)) |> 
    mutate(SplitSampleName(name)) |>
  select(name, value, trt, timePt)  |>  
  mutate(name = gsub("(DMSO|HHQ)_t(1|2|3|4)_", "", name)) |> rename(Replicate = name) |>
  mutate(timePt=factor(PrepNamesForPlots(timePt=paste0("t", timePt))$timePt, levels = levs, ordered = T))|>
           ggplot(aes(x = Replicate, y = value, fill = trt)) + 
  geom_boxplot(alpha = 0.6) + 
  facet_grid(rows = vars(trt), cols = vars(timePt)) + scale_fill_manual(values = trt_vir_cols) +
  bb_theme() + 
  ylab("log2(counts+1)") +
  theme(axis.text.x = element_text(angle = 90, size = 8,vjust = 1))
ggsave(paste0(res_path, "figs/edgeR_pseudocounts_boxplot_AftFilt", ext, ".pdf"), device = cairo_pdf)


pivot_longer(as.data.frame(pseudoCounts), cols = colnames(pseudoCounts)) |> 
    mutate(SplitSampleName(name)) |> 
  select(name, value, trt, timePt)  |>  
  mutate(name = gsub("(DMSO|HHQ)_t(1|2|3|4)_", "", name)) |> 
  rename(Replicate = name) |>
  mutate(timePt=factor(PrepNamesForPlots(timePt=paste0("t", timePt))$timePt, levels = levs, ordered = T))|>
           ggplot(aes(x = Replicate, y = value, fill = trt)) + 
  geom_violin(alpha = 0.6,trim = T,draw_quantiles = 0.5) + 
  facet_grid(rows = vars(trt), cols = vars(timePt)) +
scale_fill_manual(values = trt_vir_cols) + 
  bb_theme() + 
  ylab("log2(counts+1)") + 
  theme(axis.text.x = element_text(angle = 90, size = 8,vjust = 1))

ggsave(paste0(res_path, "figs/edgeR_pseudocounts_violin_AftFilt", ext, ".pdf"), device = cairo_pdf)
}else{
names(FullCol)<-colnames(pseudoCounts)

pivot_longer(as.data.frame(pseudoCounts), cols = colnames(pseudoCounts)) |> 
    mutate(SplitSampleName(name)) |>
  mutate(trt_vir = paste0(trt, " (", virus, ")")) |>
  select(name, value, trt_vir, timePt)  |>  
  mutate(name = gsub("(DMSO|HHQ)_(cntl|inf)_t(1|2|3|4)_", "", name)) |> rename(Replicate = name) |>
  mutate(timePt=factor(PrepNamesForPlots(timePt=paste0("t", timePt))$timePt, levels = levs, ordered = T))|>
           ggplot(aes(x = Replicate, y = value, fill = trt_vir)) + 
  geom_boxplot(alpha = 0.6) + 
  facet_grid(rows = vars(trt_vir), cols = vars(timePt)) + scale_fill_manual(values = trt_vir_cols) +
  bb_theme() + 
  ylab("log2(counts+1)") +
  theme(axis.text.x = element_text(angle = 90, size = 8,vjust = 1))

ggsave(paste0(res_path, "figs/edgeR_pseudocounts_boxplot_AftFilt", ext, ".pdf"), device = cairo_pdf, width = 12)

pivot_longer(as.data.frame(pseudoCounts), cols = colnames(pseudoCounts)) |> 
    mutate(SplitSampleName(name)) |> 
   mutate(trt_vir = paste0(trt, " (", virus, ")")) |>
  select(name, value, trt_vir, timePt)  |>  
  mutate(name = gsub("(DMSO|HHQ)_(cntl|inf)_t(1|2|3|4)_", "", name)) |> rename(Replicate = name) |>
  mutate(timePt=factor(PrepNamesForPlots(timePt=paste0("t", timePt))$timePt, levels = levs, ordered = T))|>
           ggplot(aes(x = Replicate, y = value, fill = trt_vir)) + 
  geom_violin(alpha = 0.6,trim = T,draw_quantiles = 0.5) + 
  facet_grid(rows = vars(trt_vir), cols = vars(timePt)) +
scale_fill_manual(values = trt_vir_cols) + 
  bb_theme() + 
  ylab("log2(counts+1)") + 
  theme(axis.text.x = element_text(angle = 90, size = 8,vjust = 1))

ggsave(paste0(res_path, "figs/edgeR_pseudocounts_violin_AftFilt", ext, ".pdf"), device = cairo_pdf, width = 12)  
}



# Heatmaps & PCAs ----
remove(cpm_log)
cpm_log <- cpm(y2$counts, log = TRUE)
if(subs == 'virus'){
colnames(cpm_log)<-gsub("_inf_", "_", colnames(cpm_log))
}
dmat<-round(stats::cor(cpm_log, method = "spearman"),4)

#Transform the scale from correlations
ddist<-round((-(dmat-1)/2),4)
ddist<-as.dist(ddist)

pheatmap1<-MyPheatmapDist(dmat,color = prgn, main = "Correlation of log(CPM), filtered genes", clustering_distance_cols = ddist , clustering_distance_rows = ddist)
save_pheatmap_png(pheatmap1,paste0(res_path, "figs/edgeR_heatmap1_cpmLog_corr_AftFilt", ext, ".png"), width=1600)

cts_keep<-cts[keep,]
if(sampSet != "39samp"){
poisd <- PoissonDistance(t(cts_keep), type = 'deseq')
}else{
poisd <- PoissonDistance(t(cts_keep), type = 'mle')
}

samplePoisDistMatrix <- as.matrix( poisd$dd )
rownames(samplePoisDistMatrix)<-colnames(normMat)
colnames(samplePoisDistMatrix)<-colnames(normMat)

ppois_g<-MyPheatmapDist(samplePoisDistMatrix,
         clustering_distance_rows=poisd$dd,
         clustering_distance_cols=poisd$dd, main = "Poisson distance of raw counts, filtered genes")
save_pheatmap_png(ppois_g,paste0(res_path, "figs/edgeR_heatmap2_PoisDistRaw_AftFilt", ext, ".png"), width=1600)

metadata <- data.frame(row.names = colnames(cpm_log))
metadata$trt_vir<-coldata$trt_vir
metadata$timePt <- coldata$timePt


p <- PCAtools::pca(
            mat = cpm_log,
            metadata = metadata,
            removeVar = 1-nprop) # 

rownames(p$loadings) <- as_tibble(rownames(p$loadings)) |>
  setNames("locus_tag") |>
  left_join(annot) |>
  dplyr::select(c("rowLabel")) |>
  unique() |>
  deframe() 
pdf(paste0(
  res_path, "figs/edgeR_PCAbiplots_condition",
  ext,
  "_0_AftFilt.pdf"
))
ppca0a <- PCAtools::biplot(
  p,
  showLoadings = FALSE,
  x = "PC1",
  y = "PC2",
  colby = 'trt_vir',
  shape = 'timePt',
  # to change shape by levels of an additional factor
  legendPosition = 'right',
  labSize = 2,
  pointSize = 2,
  sizeLoadingsNames = 2,
  title = "Not so pretty PCA"
)

ppca0b <- PCAtools::biplot(
  p,
  showLoadings = T,
  x = "PC1",
  y = "PC2",
  colby = 'trt_vir',
  shape = 'timePt',
  # to change shape by levels of an additional factor
  legendPosition = 'right',
  labSize = 2,
  pointSize = 2,
  sizeLoadingsNames = 2,
  ntopLoadings = 3,
  title = "Not so pretty PCA"
)

print(ppca0a)
print(ppca0b)
dev.off()
ppca0a
ppca0b
}
```

# GLM

```{r, edgeR-glm}
## Run edgeR

## Estimate Dispersions
#remove(y) #to avoid confusion
(y2 <- estimateDisp(y2, design))
mybcv<-round(sqrt(y2$common.dispersion), 4)
cat(paste0("BCV is ",mybcv, "\n" ))
fit <- glmQLFit(y2, design, robust = TRUE)


#biological CV
pdf(paste0(res_path, "figs/edgeR_bcv_and_qldisp", ext, ".pdf"))
#the red line is sqrt(y$common.dispersion)
#p51: https://bioconductor.org/packages/release/bioc/vignettes/edgeR/inst/doc/edgeRUsersGuide.pdf
plotBCV(y2)
#The QL dispersions can be estimated using the glmQLFit function, and then be visualized with the plotQLDisp function.
plotQLDisp(fit)
dev.off()
plotBCV(y2)
plotQLDisp(fit)

## Test for all
## https://github.com/gutierrez-arcelus-lab/bcellactivation/blob/master/bcell_lowinput/edger_diffexpr.R
gs <- colnames(design)

combinations <- combn(seq_len(length(gs)), 2)
if(TRUE){ # run glmTREAT() for host to narrow down DE gene list
if(subs == 'host'){
lfc <-  log2(1.5) #fold effect of |1.5|
}else{
lfc <-NULL
}
(lfc)
run_qlf <- function(i, alpha = 0.05) {

    comb_i <- combinations[ , i]
    contrasts_i <- rep(0, length(gs)) 
    contrasts_i[comb_i[1]] <- -1 #control
    contrasts_i[comb_i[2]] <- 1 #exp
    if(is_null(lfc)){
    qlf <- glmQLFTest(fit, contrast = contrasts_i)
    print(summary(decideTests(qlf, contrast=contrasts_i, adjust.method = 'BH',p.value = alpha, lfc = 0)))
    res <- 
	topTags(qlf, n = Inf, p.value = alpha) |> 
	as.data.frame() |>
	as_tibble(rownames = "gene_id")
    }else{
    tr <- glmTreat(fit, contrast=contrasts_i, lfc = lfc)
    print(summary(decideTests(tr, contrast=contrasts_i, adjust.method = 'BH',p.value = alpha, lfc = lfc)))
    
  
    res <- 
	topTags(tr, n = Inf, p.value = alpha) |> 
	as.data.frame() |>
	as_tibble(rownames = "gene_id")
}
    if (nrow(res) > 0) {

	res |>
	    mutate(group1 = gs[comb_i[2]], 
	           group2 = gs[comb_i[1]]) |>
	    dplyr::select(group1, group2, everything())

    } else {
	tibble(group1 = gs[comb_i[2]], group2 = gs[comb_i[1]])
    }

    }



library(furrr)
plan(multisession, workers = parallelly::availableCores())

#pdf(paste0(res_path, "GLM_plotMDp0.05", ext, ".pdf"))
qlf_all <- 
    future_map_dfr(1:ncol(combinations), run_qlf) 
gc()
#dev.off()
qlf_all<-qlf_all |> 
  mutate(contrast = paste0(qlf_all$group1, "v", qlf_all$group2))
qlf_all<-qlf_all |> rename(locus_tag = gene_id)
qlf_all<-qlf_all |>
    left_join(distinct(tx_to_gene, locus_tag, rowLabel), by = "locus_tag") 

qlf_all <- qlf_all |>
    select(group1, group2, contrast, locus_tag, rowLabel, everything())

qlf_all <- qlf_all |> 
  mutate(DIR = ifelse(logFC >0, "UP", ifelse(logFC < 0, "DOWN", NA)))

write_tsv(qlf_all, paste0(res_path, "tables/edgeR_GLM_DiffExpr_AllContrastsp0.05.tsv"))
}else{
qlf_all<-read_tsv(paste0(res_path, "tables/edgeR_GLM_DiffExpr_AllContrasts_p0.05.tsv"))  
}

qlf_all |>  
  group_by(contrast, .drop = FALSE) |>  
  tally() |> 
  arrange(desc(n)) |>
  gt()


```



# LRT

```{r, edgeR-lrt}
#gs <- colnames(design)
#combinations <- combn(seq_len(length(gs)), 2)
design2 <- model.matrix(~0+group)
colnames(design2) <- sub("group", "", colnames(design2))
colnames(design2)
gs2<-colnames(design2)
combinations2 <- combn(seq_len(length(gs)), 2)
#LRT
if(TRUE){
fitLRT <- glmFit(y2, design2, robust=TRUE)
run_lrt <- function(i, alpha = 0.05) {
    
    comb_i <- combinations[ , i]
    contrasts_i <- rep(0, length(gs)) 
    contrasts_i[comb_i[1]] <- -1 #control
    contrasts_i[comb_i[2]] <- 1 #exp

   lrt <- glmLRT(fitLRT, contrast = contrasts_i)
    print(summary(decideTests(lrt, contrast=contrasts_i, adjust.method = 'BH',p.value = alpha, lfc = 0)))
    #pdf(paste0(res_path, "LRT_plotMD_", gs[comb_i[1]], "v", gs[comb_i[2]], ext, ".pdf"))
  #plotMD(lrt,bg.pch=1, bg.cex=0.5,contrast = contrasts_i, ylim = c(-3,3))
 # abline(h=c(0.5,-0.5),col="dodgerblue")
  #abline(h=c(1,-1),col="#D55E00", lty = 2)
  #dev.off()
    res <- 
	topTags(lrt, n = Inf, p.value = alpha) |> 
	as.data.frame() |>
	as_tibble(rownames = "gene_id")

    if (nrow(res) > 0) {

	res |>
	    mutate(group1 = gs2[comb_i[2]], group2 = gs2[comb_i[1]]) |>
	    select(group1, group2, everything())

    } else {
	
	tibble(group1 = gs2[comb_i[2]], group2 = gs2[comb_i[1]])
    }

}

library(furrr)
plan(multisession, workers = parallelly::availableCores())
lrt_all <- 
    future_map_dfr(1:ncol(combinations), run_lrt) 
gc()

lrt_all<-lrt_all |> 
  mutate(contrast = paste0(lrt_all$group1, "v", lrt_all$group2))
lrt_all<-lrt_all |> rename(locus_tag = gene_id)
lrt_all<-lrt_all |>
    left_join(distinct(tx_to_gene, locus_tag, rowLabel), by = "locus_tag") 

lrt_all <- lrt_all |>
    select(group1, group2, contrast, locus_tag, rowLabel, everything())

lrt_all <- lrt_all |> 
  mutate(DIR = ifelse(logFC >0, "UP", ifelse(logFC < 0, "DOWN", NA)))

write_tsv(lrt_all, paste0(res_path, "tables/edgeR_LRT_DiffExpr_AllContrasts_p0.05.tsv"))
}else{
lrt_all<-read_tsv(paste0(res_path, "tables/edgeR_LRT_DiffExpr_AllContrasts_p0.05.tsv"))  
}
lrt_all |>  
  group_by(contrast, .drop = FALSE) |>  
  tally() |> 
  arrange(desc(n)) |>
  gt()

```





# Contrasts of Interest

```{r, edgeR-compare}



if(TRUE){
cl<-unique(qlf_all$contrast)
subsetCL<-unique(cl)[
  unlist(lapply(lapply(cl, function(x) SplitContrastName(contrast = x)), function(y) length(unique(y$timePt))==1))]

if(subs == 'host'){
vecKeep<-rep(NA, length(subsetCL))
for(s in 1:length(subsetCL)){
  splits<-SplitContrastName(contrast = subsetCL[s])
  uniqueT<-unique(splits$trt)
  uniqueV<-unique(splits$virus)
  if(length(uniqueT) != length(uniqueV)){
   vecKeep[s]<-T 
  }else{
    vecKeep[s]<-F
  }
}
subsetCL<-subsetCL[vecKeep]
}

saveRDS(subsetCL, file = paste0(res_path, "edgeR_ContsOfInterest", ext, ".rds"))
}else{
subsetCL<-readRDS(paste0(res_path, "edgeR_ContsOfInterest", ext, ".rds"))
}
#--- 

padj<-0.05

library(ggVennDiagram)
temp_list<- list(glm = qlf_all |> 
                   filter(contrast %in% subsetCL), 
                 lrt = lrt_all |> 
                   filter(contrast %in% subsetCL))
temp_list<-lapply(temp_list, function(x) na.omit(x))
saveRDS(temp_list, paste0(res_path, "edgeR_ContsOfInterest_p",padj, ext, ".rds"))

names(temp_list)<-c( "glm", "lrt")

for(fc in c(1.5, 1.8, 2, 2.5, 3, 4)){
lfc<-log2(fc)

temp_list$glm |> 
  filter(FDR <= padj) |>
  filter(abs(logFC)>=lfc) |>
  group_by(contrast, .drop = FALSE) |> 
  tally() |> 
  arrange(desc(n)) |>
  gt() |>
  gtsave(paste0(res_path, "figs/edgeR_glm_NrDegsPerContrastp", padj, "fc", fc, ext, ".png"))
  
  temp_list$lrt |> 
  filter(contrast %in% subsetCL) |>
  filter(FDR <= padj) |>
  filter(abs(logFC)>=lfc) |>
  group_by(contrast, .drop = FALSE) |> 
  tally() |> 
  arrange(desc(n)) |>
  gt() |>
  gtsave(paste0(res_path, "figs/edgeR_lrt_NrDegsPerContrastp", padj, "fc", fc, ext, ".png"))

to_venn_all<-lapply(temp_list, 
                    function(x) unique(x |> 
                  filter(FDR<=padj) |>
                    filter(abs(logFC)>=lfc) |>
                  pull(locus_tag)))
#names(to_venn)<-paste0("edger_", names(to_venn))

pdf(paste0(res_path, 'figs/edgeR_venn_DEGs_p', padj, 'fc',fc, '_ContsOfInterest', ext, '.pdf'))
print(ggVennDiagram(to_venn_all,force_upset = F, label_color="white"))

dev.off()
}
#
padj<-0.05
fc<-2
lfc<-log2(fc)
#if(length(subsetCL)>1){
upset_list<-vector('list', length(subsetCL))
names(upset_list)<-subsetCL
for(cont in subsetCL){

pdf(paste0(res_path, 'figs/edgeR_venn_DEGs_p', padj, 'fc',fc, '_', cont,ext, '.pdf'))
temp<-lapply(temp_list, function(x) x |> 
               filter(contrast == cont)|>
                  filter(FDR<padj) |> 
                  filter(abs(logFC)>=lfc) |> 
                  pull(locus_tag))
upset_list[[cont]]<-temp$glm
print(ggVennDiagram(temp,force_upset = F, label_color="white"))
Sys.sleep(1)
dev.off()
remove(temp)
gc()
}


upset_list<-upset_list[unlist(lapply(upset_list, function(x) length(x) !=0))]
if(length(upset_list)>1){
pdf(paste0(res_path, 'figs/edgeR_glm_upsetDEGs_p', padj, 'fc',fc,ext, '.pdf'))
print(ggVennDiagram(upset_list, force_upset = T, nintersect = 20))
dev.off()
}
## Effect of HHQ 

# contsHHQinf<- subsetCL[grepl("HHQ_inf_t(1|2|3|4)vDMSO_inf_t(1|2|3|4)", subsetCL)]
# 
# contsHHQcntl<- subsetCL[grepl("HHQ_cntl_t(1|2|3|4)vDMSO_cntl_t(1|2|3|4)", subsetCL)]
# 
# new_list<-upset_list[contsHHQinf]
# ggVennDiagram(new_list, force_upset = T)



```


# Write tables

```{r, write-excel}

## GLM
# create workbook to accumulate worsheets
wb <- createWorkbook()

# loop over export tibbles to add worksheets

options("openxlsx.maxWidth" = 40) # gene descriptions can be long

for(i in subsetCL){
    remove(tmp)
   cat(i, "\n")
   i2<-paste0(i, "_p", 0.05)
    tmp<-temp_list$glm |> 
      filter(contrast==i)
    addWorksheet(wb, sheetName = i2)
    writeDataTable(wb, sheet = i2, tmp, tableStyle = "TablestyleMedium2")
    setColWidths(wb, sheet = i2, cols = 1:ncol(tmp), widths = "auto")
}
# 
# # Save multi-sheet Excel file
saveWorkbook(wb, overwrite = T, file = paste0(res_path, "tables/edgeR_GLM_DEGsp0.05",ext,".xlsx"))

## LRT

# create workbook to accumulate worsheets
wb2 <- createWorkbook()

# loop over export tibbles to add worksheets

options("openxlsx.maxWidth" = 40) # gene descriptions can be long

for(i in subsetCL){
    remove(tmp)
   cat(i, "\n")
    i2<-paste0(i, "_p", 0.05)
    tmp<-temp_list$lrt |> 
      filter(contrast==i) 
    addWorksheet(wb2, sheetName = i2)
    writeDataTable(wb2, sheet = i2, tmp, tableStyle = "TablestyleMedium2")
    setColWidths(wb2, sheet = i2, cols = 1:ncol(tmp), widths = "auto")
}
# 
# # Save multi-sheet Excel file
saveWorkbook(wb2, overwrite = T, file = paste0(res_path, "tables/edgeR_LRT_DEGsp0.05",ext,".xlsx"))

## Exact

# create workbook to accumulate worsheets
#wb <- createWorkbook()

# loop over export tibbles to add worksheets

# options("openxlsx.maxWidth" = 40) # gene descriptions can be long
# 
# for(i in subsetCL){
#     remove(tmp)
#    cat(i, "\r")
#    i2<-paste0(i, "_p", 0.05)
#     tmp<-exact_all |> 
#       filter(contrast==i)
#     addWorksheet(wb, sheetName = i2)
#     writeDataTable(wb, sheet = i2, tmp, tableStyle = "TablestyleMedium2")
#     setColWidths(wb, sheet = i2, cols = 1:ncol(tmp), widths = "auto")
# }
# # 
# # # Save multi-sheet Excel file
# saveWorkbook(wb, overwrite = T, file = paste0(res_path, "tables/edgeR_Exact_DEGsp0.05",ext,".xlsx"))
# 

sessionInfo()

## End ----
sessionInfo() |>
  capture.output() |>
   writeLines(paste0("logs/salmon-to-edge-", subs, "-", sampSet, ".txt"))
```





# Obsolete Stuff

```{r obsolete, eval = F, include = F}


# check that groups of samples are indeed correlated

#ignore for now ---
if(FALSE){
logFC <- predFC(dge2,design,prior.count=1,dispersion=0.1)
colnames(logFC)

pdf(paste0(res_path, "corrplot_edgeR", ext, ".PDF"))
#corrplot::corrplot(stats::cor(logFC[,c(2:5)]),type = "lower")
#if(subs == 'host'){
corrplot::corrplot(stats::cor(logFC), type = "lower")
#corrplot::corrplot(stats::cor(logFC[,c(6:20)]), type = "lower")
#}else if(sampSet == '29samp'){
#corrplot::corrplot(stats::cor(logFC[,c(6:10)]), type = "lower")
#}
dev.off()
}


plotSmear(dge2, pair = c(cond1.name, cond2.name), de.tags = edgeR_glm_p0.05_lfc0.5_inft4$gene_id, 
					main = "FC plot using common dispersion")
abline(h=c(0.5,-0.5),col="dodgerblue")

#https://rpubs.com/natmurad/WGCNA
library(WGCNA)
#Enable multithread
# Set WGCNA cores
allowWGCNAThreads(parallelly::availableCores())

#Expression data
expression <-rcounts[keep2,]
sample_table <- 
    tibble(sample_id = colnames(expression)) |>
    extract(sample_id, c("group"), "[^_]+_(.+)", remove = FALSE) |>
    column_to_rownames("sample_id")
sample_data<-coldata |> column_to_rownames("names")


#Group data in a dendogram to check outliers
sampleTree = hclust(dist(expression), method = "average")



par(cex = 0.6)
par(mar = c(0,4,2,0))
plot(sampleTree, main = "Sample clustering to detect outliers", sub="", xlab="", cex.lab = 1.5, 
     cex.axis = 1.5, cex.main = 2)

#Plot a line showing the cut-off
abline(h = 120000, col = "red") #This value of 31000 was chosen based on my data, you need to check the best value to your data

#Determine clusters below the line
#help("cutreeStatic")
clust = cutreeStatic(sampleTree, cutHeight = 120000, minSize = 10)
#table(clust)
#clust

lrt<- glmLRT(fitLRT, contrast = my.contrasts[,"HHQ_DMSO_t4"])
pdf(paste0(res_path, "edgeR_lrt_plotMD_Inf_t4", ext, ".pdf"))
plotMD(lrt,bg.pch=1, bg.cex=0.5)
abline(h=c(0.5,-0.5),col="dodgerblue")
dev.off()
plotMD(lrt,bg.pch=1, bg.cex=0.5)
abline(h=c(0.5,-0.5),col="dodgerblue")
edgeR_lrt_FDR_inft4<-topTags(lrt, n = Inf)$table 

summary(decideTests(lrt, contrast=my.contrasts[,"HHQ_DMSO_t4"], adjust.method = 'BH',p.value = padj_t, lfc = lfc_t))
#Add to edge R list
edger_HHQ_DMSO_t4$lrt<-edgeR_lrt_FDR_inft4

#compare
library(ggVennDiagram)

to_venn<-lapply(edger_HHQ_DMSO_t4, function(x) x |> 
                  filter(FDR<0.05) |> filter(abs(logFC)>=0.5) |> 
                  pull(gene_id))
names(to_venn)<-paste0("edger_", names(to_venn))

pdf(paste0(res_path, 'venn_DEGs_EdgeR_p0.05_lfc0.5_Inf_t4', ext, '.pdf'))
ggVennDiagram(to_venn,force_upset = F)
dev.off()
(to_venn_deseq<-list(deseq_glm = genes_to_plot_p0.05_fc0.5, deseq_lrt = genes_to_plot_lrt)) 
                     #edgeR_glm = edgeR_glm_p0.05_lfc0.5$gene_id, edgeR_lrt = edgeR_lrt_p0.05_lfc0.5$gene_id))

pdf(paste0(res_path, 'venn_DEGs_deseq_p0.05_lfc0.5_Inf_t4', ext, '.pdf'))
ggVennDiagram(to_venn_deseq,force_upset = F)
dev.off()
pdf(paste0(res_path, "venn_DEGs_p0.05_lfc0.5_Inf_t4", ext, ".pdf"))
ggVennDiagram(c(to_venn, to_venn_deseq), force_upset = T)
dev.off()

# 
# mylist_p0.05_lfc1<-list(deseq_glm = genes_to_plot_p0.05_fc1, deseq_lrt = genes_to_plot_lrt_p0.05_fc1, edgeR_glm = edgeR_glm_p0.05_lfc1$gene_id, edgeR_lrt = edgeR_lrt_p0.05_lfc1$gene_id)
# 
# pdf(paste0(res_path, 'venn_DEGs_p0.05_lfc1_Inf_t4', ext, '.pdf'))
# ggVennDiagram(mylist_p0.05_lfc1,force_upset = F)
# dev.off()

if(TRUE){
#any DEGs between DMSO_inf_t4 and HHQ_inf_t4
n1<-length(colnames(coefficients(fit)))
cnt<-which(grepl("DMSO_inf_t4",colnames(coefficients(fit))))
exp<-which(grepl("HHQ_inf_t4",colnames(coefficients(fit))))
all<-rep(0, n1)
all[exp]<- 1
all[cnt]<- -1
qlf <- glmQLFTest(fit, contrast=all)
#genes with FDR<0.05
summary(decideTests(qlf, lfc = 0, p.value = 0.05, adjust.method = "BH"))


lrt<- glmLRT(fit, contrast = all)
}
#-----
```


```{r, edgeR-exact, eval = F, include = F}


#gs
if(FALSE){
run_exact <- function(i, alpha = 0.05) {
    
    comb_i <- combinations[ , i]
    comb_i[1]
    contrasts_i <- rep(0, length(gs)) 
    contrasts_i[comb_i[1]] <- -1
    contrasts_i[comb_i[2]] <- 1
    
    #qlf <- glmQLFTest(fit, contrast = contrasts_i)
    exactT<-exactTest(y2, pair = comb_i)
   print(summary(decideTests(exactT, contrast=contrasts_i, adjust.method = 'BH',p.value = alpha, lfc = 0)))
    #pdf(paste0(res_path, "Exact_plotMD_", gs[comb_i[1]], "v", gs[comb_i[2]], ext, ".pdf"))
  #plotMD(exactT,bg.pch=1, bg.cex=0.5, ylim = c(-3,3))
  #abline(h=c(0.5,-0.5),col="dodgerblue")
  #abline(h=c(1,-1),col="#D55E00", lty = 2)
  #dev.off()
    res <- 
	topTags(exactT, n = Inf, p.value = alpha) |> 
	as.data.frame() |>
	as_tibble(rownames = "gene_id")

    if (nrow(res) > 0) {

	res |>
	    mutate(group1 = gs[comb_i[1]], group2 = gs[comb_i[2]]) |>
	    select(group1, group2, everything())

    } else {
	
	tibble(group1 = gs[comb_i[1]], group2 = gs[comb_i[2]])
    }

}

library(furrr)
plan(multisession, workers = parallelly::availableCores())
exact_all <- 
    future_map_dfr(1:ncol(combinations), run_exact) 

exact_all<-exact_all |> 
  mutate(contrast = paste0(exact_all$group1, "v", exact_all$group2))
exact_all<-exact_all |>
    left_join(distinct(tx_to_gene, gene_id, transcript_id), join_by(gene_id)) 

exact_all <- exact_all |>
    select(group1, group2, contrast, gene_id, transcript_id, everything())
write_tsv(exact_all, paste0(res_path, "tables/edgeR_EXACT_DiffExpr_AllContrasts_p0.05.tsv"))
}else{
exact_all<-read_tsv(paste0(res_path, "tables/edgeR_EXACT_DiffExpr_AllContrasts_p0.05.tsv"))  
}
```

